### PR TITLE
fix: compatibility with angular 13

### PR DESCRIPTION
**Pull request by cedricduffournet**
Package does not work with `angular v13` (many errors displayed in html file).

Updating `language-server` to `13.0.0` and  `typescript` to `4.4.4` fix the issue.

I deleted all references to experimental-ivy as it does not exist anymore

### CODE REVIEW

**Comment by iamcco** [comment]
Need to track all patch in the origin repo instead of just upgrade angular version. Also it seems it does not work on my angular 11 project.

PS. do not apply code format on the code, it will make it more harder to track patch from upstream change.

**Comment by cedricduffournet** [comment]
ha yes, sorry about the code format, I did not check correcly. 
I thought you could make different tag depending on angular version.
I close the PR and I let you manage the update ?

**Comment by cedricduffournet** [comment]
Actually on vscode there is a new option `angular.view-engine` depending on this option, they load language-service v12.2.12 or v13 to make it compatible with old angular version

**Comment by cedricduffournet** [comment]
I fix code format

**Comment by iamcco** [comment]
I have update all change from upstream https://github.com/iamcco/coc-angular/pull/44

**Comment by cedricduffournet** [comment]
thank you !

**Pull request closed without merging**
